### PR TITLE
2to3

### PR DESCRIPTION
**Pull request by johannct**
merge 2to3 into origin master now that DarkEnergySurvey/ugali has pulled the branch.

### CODE REVIEW

**Comment by kadrlica** [comment]
I think it's better to do a merge from DarkEnergySurvey/ugali to keep synced. I'm going to try to accomplish this...

**Comment by johannct** [comment]
yeah, maybe. I do not know what is the proper usage. The 2to3 branch should disappear I believe.

**Comment by kadrlica** [comment]
Yeah, I'm going to work on this, but it will probably be a hackish solution.

**Comment by kadrlica** [comment]
Ok, master should be clean and tracking upstream master (I ended up moving branches and then checking out upstream clean and committing). I don't really know the "right" way to use git here. I think that we want to submit PRs from to DarkEnergySurvey master, and then pull from DarkEnergySurvey master to lsstdarkmatter master (rather than PRing to both).

**Comment by johannct** [comment]
ok, noted

**Pull request merged**
